### ISSUE TITLE
Compiling libraries with _grompy from modified source

### ISSUE THREAD

**Issue by martinhoefling** [GromPy/GromPy#1]
We should compile libraries with _grompy suffix from the modified source. E.g. libmd_grompy.so similar to the default _d for double precision. This would allow side installation of the modified grompy library and the default gromacs libraries.

**Comment by rpool** [comment]
Yeah that makes sense. It also depends on the way the package will be ported to the GROMACS dev tree...

**Comment by martinhoefling** [comment]
I guess grompy is totally outdated nowadays
